Update github-actions-aks-dev-workflow.yml

diff --git a/.github/workflows/github-actions-aks-dev-workflow.yml b/.github/workflows/github-actions-aks-dev-workflow.yml
--- a/.github/workflows/github-actions-aks-dev-workflow.yml
+++ b/.github/workflows/github-actions-aks-dev-workflow.yml
@@ -58,16 +58,8 @@ jobs:
           ref: dev
           token: ${{ secrets.SERVICE_ACCOUNT_PAT }}
 
-      - name: Setup PHP
-        uses: shivammathur/setup-php@v2
-        with:
-          php-version: '8.4'
-
       - name: Install Composer dependencies
         run: composer install --no-interaction --prefer-dist --optimize-autoloader
-
-      - name: Install Doppler CLI
-        run: curl -Ls https://cli.doppler.com/install.sh | sh
 
       - name: Run DB migrations
         run: doppler run -- php artisan migrate --force
@@ -257,3 +249,59 @@ jobs:
                 "text": "❌ Pipeline failed\nRepository: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nCommit: ${{ github.sha }}\nAuthor: ${{ github.event.head_commit.author.name }}\nMessage: ${{ github.event.head_commit.message }}\nURL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
               }' \
           "${{ secrets.IM_NONPROD_DEPLOYMENT_WEBHOOK_URL }}"
+
+#  deploy:
+#    needs: [detect-changes, build-push]
+#    runs-on: ubuntu-latest
+#    permissions:
+#      id-token: write
+#      contents: read
+#
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v2
+#
+#      - name: Configure AWS credentials
+#        uses: aws-actions/configure-aws-credentials@v4
+#        with:
+#          role-to-assume: "${{ secrets.AWS_ROLE_ARN }}"
+#          role-session-name: "${{secrets.AWS_ROLE_NAME}}"
+#          aws-region: me-central-1
+## Installation Required Packages
+#      - name: Install AWS CLI
+#        run: |
+#          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+#          unzip awscliv2.zip
+#          sudo ./aws/install --update
+#          aws --version    
+#      - name: Install kubectl
+#        run: |
+#          curl -LO "https://dl.k8s.io/release/v1.31.1/bin/linux/amd64/kubectl"
+#          chmod +x ./kubectl
+#          sudo mv ./kubectl /usr/local/bin/kubectl
+#          kubectl version --client 
+#      - name: Update kubeconfig
+#        run: |
+#          aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region me-central-1
+#      - name: Deploy to Kubernetes
+#        run: |
+#          # Run any Kubernetes deployment commands here, with environment variables loaded from Doppler
+#
+#          IMAGE_TAG=${{ needs.build-push.outputs.image_tag }}
+#          BUILD_NUMBER=${{ needs.build-push.outputs.build_number }}
+#          echo "Deploying image with tag: $IMAGE_TAG and build number: $BUILD_NUMBER"
+#
+#          sed -i.bak "s|DOCKER_IMAGE|$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" k8s/$ENVIRONMENT/$PROJECT-deployment.yaml
+#
+#          kubectl apply -f k8s/$ENVIRONMENT/ --namespace=$NAMESPACE
+#          #kubectl apply -f k8s/ingress/ --namespace=$NAMESPACE
+#          kubectl rollout restart deployment $DEPLOYMENT_NAME  --namespace=$NAMESPACE
+#        
+#      # Verify Deployment and Rollback in Case of Failure
+#      #- name: Verify deployment
+#      #  run: |
+#      #    kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} -n default
+#      #    if [ $? -ne 0 ]; then
+#      #      kubectl rollout undo deployment/${{ env.DEPLOYMENT_NAME }} -n default
+#      #      exit 1
+#      #    fi
